/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multimodal.OneRecognizer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author hakje
 */
public class Icar extends javax.swing.JFrame implements GesteListener {

    private List<Geste> learnedGest = new ArrayList<>();
    private PanelDessin panelLearning, panelReco;

    /**
     * Creates new form Icar
     */
    public Icar() {
        initComponents();
        panelLearning = new PanelDessin();
        panelReco = new PanelDessin();

        jPanel3.add(panelReco);
        jPanel4.add(panelLearning);
        panelLearning.setBorder(BorderFactory.createLineBorder(Color.red));
        panelReco.setBorder(BorderFactory.createLineBorder(Color.blue));
        setSize(800, 500);

        panelLearning.setPanelLearning(true);
        panelLearning.setGestureListener(this);

        panelReco.setPanelLearning(false);
        panelReco.setGestureListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelRecognition = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());
        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabelRecognition.setBackground(new java.awt.Color(255, 204, 204));
        jLabelRecognition.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabelRecognition.setText("Geste reconnu");
        jPanel5.add(jLabelRecognition);
        jLabelRecognition.getAccessibleContext().setAccessibleName("labelRecognition");

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void gesteFinished(Geste geste, boolean isLearning) {
        geste.compute();
        
        if (isLearning) {
            //stocker
            String retour = JOptionPane.showInputDialog(this, "Veuillez saisir la commande correspondante", "carre");

            System.out.println("NOM COMMAND : "+retour);
            
            if(retour != null) {
                geste.setCommand(retour);
                learnedGest.add(geste);
            }

            //panelReco.showGeste(geste.getMyPoints());
        } 
        else {
            //comparer
            recognizeGesture(geste);
        }
    }

    @Override
    public void toLessPoint() {
        jLabelRecognition.setText("Geste reconnu : geste trop petit ! t'as fais exprés ou quoi ? ");
    }

    
    
    private void recognizeGesture(Geste geste) {
        Geste reco = new Geste();
        int bestDistance = 0;
        String cmd="";
        
        for (Geste learnedGest : learnedGest) {                  
            int sommeDistance = 0;
            for (int i = 0; i < learnedGest.getMyPoints().size(); i++) {
                sommeDistance += geste.getMyPoints().get(i)
                        .distance(learnedGest.getMyPoints().get(i).x,
                                learnedGest.getMyPoints().get(i).y);
            }

            if (bestDistance == 0) {
                reco = learnedGest;
                bestDistance = sommeDistance;
            } else {
                if (sommeDistance < bestDistance ) {
                    reco = learnedGest;
                    bestDistance = sommeDistance;
                }
            }
            System.out.println("BEST DISTANCE : "+bestDistance);
            
        }
        
        if(bestDistance > 8000) {
            System.out.println("DANS IF : "+bestDistance);
            cmd = "Geste non reconnu";
        } 
        else {
            cmd=reco.getCommand();
        }
        
        jLabelRecognition.setText("Geste reconnu : " + cmd);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Icar().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRecognition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

}
