/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multimodal.OneRecognizer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author hakje
 */
public class Icar extends javax.swing.JFrame implements GesteListener {
    private List<Geste> learnedGest = new ArrayList<>();
    private PanelDessin panelLearning, panelReco;
    
    
    
    /**
     * Creates new form Icar
     */
    public Icar() {
        initComponents();
        panelLearning = new PanelDessin();
        panelReco = new PanelDessin();

        jPanel2.add(panelLearning, BorderLayout.EAST);        
        jPanel2.add(panelReco, BorderLayout.WEST);        
        panelLearning.setBorder(BorderFactory.createLineBorder(Color.black));
        panelReco.setBorder(BorderFactory.createLineBorder(Color.blue));
        setSize(800, 500);
        
        panelLearning.setPanelLearning(true);
        panelLearning.setGestListener(this);
        
        panelReco.setPanelLearning(true);
        panelReco.setGestListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelRecognition = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldApprentissage = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabelRecognition.setText("Geste reconnu");
        jPanel5.add(jLabelRecognition);
        jLabelRecognition.getAccessibleContext().setAccessibleName("labelRecognition");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldApprentissage.setText("Tapez le geste à apprendre");
        jTextFieldApprentissage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApprentissageActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldApprentissage);

        jButtonValider.setText("Valider");
        jPanel3.add(jButtonValider);

        jPanel5.add(jPanel3);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApprentissageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApprentissageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApprentissageActionPerformed

    
    @Override
    public void gesteFinished(Geste geste, boolean isLearning) {
        if(isLearning) {
            //stocker
            String retour = JOptionPane.showInputDialog(this, "le message", "VALEUR INITIALE");
            
            geste.setCommand(retour);
            geste.compute();
            learnedGest.add(geste);
            
            panelReco.showGeste(geste.getMyPoints());
        }
        else {
            //comparer
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Icar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Icar().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabelRecognition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldApprentissage;
    // End of variables declaration//GEN-END:variables

  
}
